### ISSUE TITLE
How plug plugin to the game?

### ISSUE THREAD

**Issue by NexSqaud** [leftspace89/LSFlatPM#1]
I try to copy example plugins dll files to %temp% but in game is nothing changed.

**Comment by leftspace89** [comment]
sorry for late answer..

what is your plugin name ? is that plugin contains DLSP_ prefix ?

**Comment by leftspace89** [comment]
and did you run the core app ? for plugin load ??

**Comment by NexSqaud** [comment]
Core app? I copied example plugins from your repository to %temp%. There is no core app. Plugin name contains LSP_ prefix.

**Comment by leftspace89** [comment]
https://memoryhackers.org/konular/pubg-mobile-dword-vip-r3-beta-v2-4-march-2019.70425/

core app is here.

and for Developer Plugins Plugin prefix Should be DLSP_

**Comment by NexSqaud** [comment]
your plugins are loading but not working. Game version 0.12.0.11023
