### ISSUE TITLE
Can I port it to SmartGaga?

### ISSUE THREAD

**Issue by sethstha** [leftspace89/LSFlatPM#12]
I tried porting the chinese version of simple ESP to SmartGaga with success but it is CPU heavy. I am basically trying to develop ESP with Radar for SGaGa. I have also did a great bypass with 160+ matches played.

**Comment by DarkneSsDz** [comment]
> I tried porting the chinese version of simple ESP to SmartGaga with success but it is CPU heavy. I am basically trying to develop ESP with Radar for SGaGa. I have also did a great bypass with 160+ matches played.

hello sir , can you please share how did you port it to smartgaga i mean i been trying but it always refuses to let me draw on smartgaga i think it needs driver to read the process a small help would be much appreciated amte ^^

**Comment by leftspace89** [comment]
it works on smartgaga.
