### ISSUE TITLE
ESPs Stopped Working After Tencent Update

### ISSUE THREAD

**Issue by hammad2224** [leftspace89/LSFlatPM#14]
Dear LeftSpace,

The ESPs have stopped working after the update.
Can you please do your magic and make it work again

Thanks 
Regards,
Hammad

**Comment by leftspace89** [comment]
I know.. Im working on it.

**Comment by leftspace89** [comment]
its updated.

**Comment by hammad2224** [comment]
Thanks to our Hero leftspace89

Regards,
From All
