### ISSUE TITLE
Payload Mode Release New Items Not Displayed

### ISSUE THREAD

**Issue by hammad2224** [leftspace89/LSFlatPM#19]
Dear LeftSpace,

New payload mode is released. and there are tons of new items introduced in that version.
We are unable to see any because Memory hack does not show them.

Is it possible to add those items in.
For example Helicopters, Garnade launchers, Air strike caller, vehical repair kits etc

Thanks 
Regards,
Hammad Rafique

**Comment by leftspace89** [comment]
I will look at theese items.

**Comment by hammad2224** [comment]
Thanks Sir
