### ISSUE TITLE
Core App

### ISSUE THREAD

**Issue by hammad2224** [leftspace89/LSFlatPM#2]
If these files are placed as it is in temp folder. Then we will require the core app to load these dlls.
Where can we download the Core App?

Any code to load the dlls will be useful

**Comment by leftspace89** [comment]
https://memoryhackers.org/konular/pubg-mobile-dword-vip-r3-beta-v2-4-march-2019.70425/

core app is here.

**Comment by hammad2224** [comment]
Dear leftspace89,
Thanks for the link. The file downloaded tells about virus. which we understand might be hooks detected as virus by the anti virus.
https://ibb.co/yXMRDPb
<a href="https://ibb.co/yXMRDPb"><img src="https://i.ibb.co/wRbLTgx/Virus-Detected.png" alt="Virus-Detected" border="0"></a>

is it possible to upload c# code just to load specific dlls like LSP_Radar.dll
so we could test the independent functionality

Thanks 
Regards,
Hammad Rafique

**Comment by hemnn** [comment]
hello  leftspace89,
i just need one thing even in the forume i requested, awareness and Skelton  in a clean core app, ready to pay for it...

**Comment by leftspace89** [comment]
What u mean clean core ? its already virus safe. that just edits your hosts file but its not that important.

**Comment by hemnn** [comment]
leftspace89 yah i know dear. actually the app is not that stable it works once and stoping working for a day or stucks on " waiting for web site" i mean the core that load the hack faster

**Comment by hammad2224** [comment]
I think he means that just specific functionalities not all of them. So app can load faster.
For example just a simple radar functionality nothing else.
I am in for that too. Ready to pay for your exellent work
