### ISSUE TITLE
Item ESP

### ISSUE THREAD

**Issue by AhmedZero** [leftspace89/LSFlatPM#8]
Item ESP dont detect Flare Gun please fix it.

**Comment by hammad2224** [comment]
Compensators not getting detected
Quick Draw Extended Megs not getting detected.
SKS not getting detected.
Suppressors not Getting detected.
Ammo.s not getting detected.
Can you please fix them?

**Comment by hammad2224** [comment]
![File1](https://user-images.githubusercontent.com/10448430/59982480-291bb880-960b-11e9-97b8-b6b2e6dc6059.png)

**Comment by hammad2224** [comment]
![File2](https://user-images.githubusercontent.com/10448430/59982490-38026b00-960b-11e9-970f-041ed9bd372e.png)

**Comment by leftspace89** [comment]
I can see u created ur own Radar :) u can share.

and nothing I can do about item esp. its is what it is :) I can't fix that sorry.

**Comment by hammad2224** [comment]
Dear LeftSpace89,

Thanks to you the code is yours. i just modified your code to make it faster and reserve less space using Diagnostic Tools (VS Profiler). You can have the code and if you add that in the current radar then. it will make it run faster as it will not require to load DLSP_Radar separately.

Thanks 
Regards
Hammad Rafique
[DLSP_Radar.zip](https://github.com/leftspace89/LSFlatPM/files/3349165/DLSP_Radar.zip)

**Comment by hammad2224** [comment]
Talking about  the things not getting detected there is another free software that gives you the option to detect everything even the drops placements compansators ammos. i can provide the link to the software if you want. May be we can find  the offsets for those items and add them here?
Let me know if i can help in any way

Thanks 
Regards,
Hammad Rafique

**Comment by hammad2224** [comment]
Dear LeftSpace89,

Can you please modify the code to load specific LSP.1
If you need the code for that please do let me know i will write the code and send it to you. so it could save your time.

Thanks 
Regards,
Hammad Rafique

**Comment by leftspace89** [comment]
why u need load specific plugin ? did that long time ago. didnt add cuz its will bring complex usage.

![image](https://user-images.githubusercontent.com/13282563/64069208-d8998a80-cc4d-11e9-9458-f4015d4bf3f8.png)

**Comment by hammad2224** [comment]
Dear LeftSpace89,

First of all thanks for adding CRadar in. We do not use our own radar anymore.
We do not use some of the plugins and we cant turn them off either like SuspScore.
We also have custom DLSPs which has enhanced code to run faster using your sdk FlatPMSDK.dll to accommodate the low spec processors and PCs. and their are modifications like Aiming at you with Gun Name etc..

Can we please get this Executable so we could only load specific dlls when running the app.

Thanks 
Regards,
Hammad Rafique

**Comment by leftspace89** [comment]
how much cpu does it consume?

**Comment by hammad2224** [comment]
CPU usage is different on different specs.Good laptop do not bother that much but on i5 1st to 4th generation they struggle. Game jams if memory hack is also running.
Memory usage is the main issue. there are memory leaks which causes somehow the memory to reach to 89% usage. and then computer start using free space on harddisk as RAM which give Halts to the PCs for 3 seconds and 5 seconds.

There are no IDisposable methods for the classes and proper GC collector calling. which we have included in our DLSPs.

I can give u exact graph maps if you need from the profiler.

Regards,
Hammad

**Comment by leftspace89** [comment]
yeah cuz their instances creating only one time (once ). I don't have to dispose them.

**Comment by leftspace89** [comment]
but you should share your (optimized) plugins for anyone. there is no point keeping private. :)

**Comment by leftspace89** [comment]
today I saw memory leaks. KernelMODE ReadProcessMemory causes this issue. gonna fix that issue next patch...

**Comment by leftspace89** [comment]
![image](https://user-images.githubusercontent.com/13282563/64308955-bbddb980-cfa3-11e9-84f1-1ebb4285b187.png)

fixed memory leak on ReadMemory..

**Comment by hammad2224** [comment]
Dear Leftspace89,

I am not keeping anything private. Credit goes to you for the code. we just optimized it. I did not share it because no one asked for it. But if you need i can upload the code for all the plugins. and you can put the code in LSFlatPM/FlatSDK/examples/  for everyone.

Can you please share the plugin loader 

Thanks 
Regards,
Hammad

**Comment by hammad2224** [comment]
Here is the code for Awareness we do not use that much bust still optimized.
you can load this in LSFlatPM/FlatSDK/examples/ 
[DLSP_Awareness.zip](https://github.com/leftspace89/LSFlatPM/files/3583824/DLSP_Awareness.zip)

**Comment by hammad2224** [comment]
I will upload all one by one.
I am doing further modification in ESPs
Different colors for different team members this is yet to be done
Once done i will upload that one too

**Comment by leftspace89** [comment]
yeah I tried that but colors should be visible.. not like black or dark green..

**Comment by hammad2224** [comment]
i will use colors hex  codes as an xml list in temp so anyone can have their own favourite colors assigned.
Its hard to debate colors and i am not good at that. so thought to give option to the user.
I might add a selection list for the user to select and display their chosen items in the map.

Thanks 
Regards,
Hammad

**Comment by leftspace89** [comment]
![image](https://user-images.githubusercontent.com/13282563/64499242-f48dd380-d2c0-11e9-8b38-620f6dfe82b2.png)

Writing Core App With C++ 
This Performance is awful!

atleast better than c# for now :)

**Comment by hammad2224** [comment]
Let me know if i can help in any way 

Best Regards,
Hammad Rafique

**Comment by hammad2224** [comment]
please do something to detect the Compensators and Quickdraw extended megs these are the only thing missing in Memories Hack, Please i request you add these one in too somehow.

We will love you forever,

**Comment by nadir1122** [comment]
Sorry for being late. I am new to programming. Would you please tell me how to use the compiled library?
